### ISSUE TITLE
set.php gives type error for ServerResponse::__construct()

### ISSUE THREAD

**Issue by danielberlin** [akalongman/php-telegram-bot#38]
When I set up the bot as described in README.md and call set.php, I get:

```
PHP Catchable fatal error:  Argument 1 passed to Longman\\TelegramBot\\Entities\\ServerResponse::__construct() must be of the type array, null given, called in /myproject/vendor/longman/telegram-bot/src/Request.php on line 152 and defined in /myproject/vendor/longman/telegram-bot/src/Entities/ServerResponse.php on line 26
```

**Comment by MBoretto** [comment]
I can't reproduce the problem.. it seem related to curl.
In 0.17.2 Exceptions are logged this can help to understand the problem.

**Comment by danielberlin** [comment]
No exception is logged, the described error above is only visible in the web server's error_log. Should I update curl? What is the minimum required version of curl? Do I need curl for hook mode? I don't think so.

**Comment by MBoretto** [comment]
My version of curl is 7.35.0 , curl is used to make all the requests to telegram.

**Comment by danielberlin** [comment]
But curl is only used for getUpdate? Since I use hook-example.php, I think it doesn't use curl or does it?

**Comment by MBoretto** [comment]
Curl is used for get update, set Web hook and to send any messages to the chat

**Comment by danielberlin** [comment]
OK, I think I have to debug my curl which is 7.29.0. Do you have a recommendation where to start from this error on?

```
Catchable fatal error: Argument 1 passed to Longman\TelegramBot\Entities\ServerResponse::__construct() must be of the type array, null given, called in /www/bot/vendor/longman/telegram-bot/src/Request.php on line 151 and defined in /www/bot/vendor/longman/telegram-bot/src/Entities/ServerResponse.php on line 26
```

**Comment by MBoretto** [comment]
Try to:
- Run phpunit as descibed in the CONTRIBUTING.mb
- Change the line https://github.com/akalongman/php-telegram-bot/blob/master/src/Request.php#L141
with:
``` if (empty($result) | is_null($result)) { ```

Then we will see

**Comment by danielberlin** [comment]
phpunit gives:

```
==== Redirecting to composer installed version in vendor/phpunit ====

PHPUnit 4.1.6-6-g43914fa by Sebastian Bergmann.

Configuration read from /www/tgbot/vendor/longman/telegram-bot/phpunit.xml.dist

.................

Time: 53 ms, Memory: 4.00Mb

OK (17 tests, 68 assertions)
```

Changing the line still results in

`PHP Catchable fatal error:  Argument 1 passed to Longman\\TelegramBot\\Entities\\ServerResponse::__construct() must be of the type array, null given, called in /myproject/vendor/longman/telegram-bot/src/Request.php on line 152 and defined in /myproject/vendor/longman/telegram-bot/src/Entities/ServerResponse.php on line 26`

Help and ideas highly appreciated. Thank you.

**Comment by MBoretto** [comment]
What you find inside? 
```var_dump($result);```

**Comment by danielberlin** [comment]
Where should I put `var_dump($result);`, in Request.php#L141? But then how do I get the output when Telegram is requesting my script? Should I access it from the browser? It should be written to the MySQL (or any other) log...

**Comment by MBoretto** [comment]
In hotfix branch I pushed some commits to trace curl errrors (If any) with Exception.

**Comment by danielberlin** [comment]
Thanks. But where do the Exceptions go?
I don't see them neither in TelegramException.log nor in error_log (still getting `Argument 1 passed to Longman\\TelegramBot\\Entities\\ServerResponse::__construct() must be of the type array, null given`).

**Comment by MBoretto** [comment]
I've  implement a logging system for curl request and response, just set verbosity to 3 as explained in the hotfix readme. 
Exception are stored in the main dir of the  project if are thrown, here.s the name of the file:
https://github.com/akalongman/php-telegram-bot/blob/master/src/Exception/TelegramException.php#L19

**Comment by danielberlin** [comment]
The logging system now helped to track down the problem to the following logged exceptions:

```
{"update_id":12345,
"message":{"message_id":123,"from":{"id":12345,"first_name":"myName","username":"myUserName"},"chat":{"id":12345,"first_name":"myName","username":"myUserName","type":"private"},"date":1445813422,"text":"\/help"}}
Verbose curl output:
* About to connect() to api.telegram.org port 443 (#13)
*   Trying 149.154.167.200...
* Connected to api.telegram.org (149.154.167.200) port 443 (#13)
[SSL verbose messages]
&gt; POST /botbot123456:myHash/sendMessage HTTP/1.1
Host: api.telegram.org
Accept: */*
Content-Length: 593
Expect: 100-continue
Content-Type: multipart/form-data; boundary=----------------------------6f5ad22da508

&lt; HTTP/1.1 100 Continue
&lt; HTTP/1.1 302 Moved Temporarily
&lt; Server: nginx/1.6.2
&lt; Date: Sun, 25 Oct 2015 23:39:13 GMT
&lt; Content-Type: text/html
&lt; Content-Length: 160
&lt; Connection: keep-alive
&lt; Location: https://core.telegram.org/bots
&lt; Strict-Transport-Security: max-age=31536000; includeSubdomains
* HTTP error before end of send, stop sending
&lt; 
* Closing connection 13

<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```

I have no clue what causes this error. Do you have further suggestions how to debug this?

**Comment by danielberlin** [comment]
The problem is that my API key was entered in a wrong format. Unfortunately, neither api.telegram.org nor php-telegram-bot displayed an error regarding this.
